/**
 * Every IANA time zone the runtime knows about (418 of them),
 * generated from Intl.supportedValuesOf("timeZone") and sorted west to east.
 *
 * The UTC offsets in the labels are computed once at generation time against a
 * fixed reference date, deliberately: calculating them at render time would give
 * different answers on the server and in the browser and break hydration. They
 * are indicative — the IANA id is what gets stored and what resolves DST
 * correctly downstream.
 */
export const TIMEZONES = [
  { value: "Pacific/Midway", label: "(UTC−11:00) Midway — Pacific/Midway" },
  { value: "Pacific/Niue", label: "(UTC−11:00) Niue — Pacific/Niue" },
  { value: "Pacific/Pago_Pago", label: "(UTC−11:00) Pago Pago — Pacific/Pago_Pago" },
  { value: "America/Adak", label: "(UTC−10:00) Adak — America/Adak" },
  { value: "Pacific/Honolulu", label: "(UTC−10:00) Honolulu — Pacific/Honolulu" },
  { value: "Pacific/Rarotonga", label: "(UTC−10:00) Rarotonga — Pacific/Rarotonga" },
  { value: "Pacific/Tahiti", label: "(UTC−10:00) Tahiti — Pacific/Tahiti" },
  { value: "Pacific/Marquesas", label: "(UTC−09:30) Marquesas — Pacific/Marquesas" },
  { value: "America/Anchorage", label: "(UTC−09:00) Anchorage — America/Anchorage" },
  { value: "America/Juneau", label: "(UTC−09:00) Juneau — America/Juneau" },
  { value: "America/Metlakatla", label: "(UTC−09:00) Metlakatla — America/Metlakatla" },
  { value: "America/Nome", label: "(UTC−09:00) Nome — America/Nome" },
  { value: "America/Sitka", label: "(UTC−09:00) Sitka — America/Sitka" },
  { value: "America/Yakutat", label: "(UTC−09:00) Yakutat — America/Yakutat" },
  { value: "Pacific/Gambier", label: "(UTC−09:00) Gambier — Pacific/Gambier" },
  { value: "America/Los_Angeles", label: "(UTC−08:00) Los Angeles — America/Los_Angeles" },
  { value: "America/Tijuana", label: "(UTC−08:00) Tijuana — America/Tijuana" },
  { value: "America/Vancouver", label: "(UTC−08:00) Vancouver — America/Vancouver" },
  { value: "Pacific/Pitcairn", label: "(UTC−08:00) Pitcairn — Pacific/Pitcairn" },
  { value: "America/Boise", label: "(UTC−07:00) Boise — America/Boise" },
  { value: "America/Cambridge_Bay", label: "(UTC−07:00) Cambridge Bay — America/Cambridge_Bay" },
  { value: "America/Ciudad_Juarez", label: "(UTC−07:00) Ciudad Juarez — America/Ciudad_Juarez" },
  { value: "America/Creston", label: "(UTC−07:00) Creston — America/Creston" },
  { value: "America/Dawson", label: "(UTC−07:00) Dawson — America/Dawson" },
  { value: "America/Dawson_Creek", label: "(UTC−07:00) Dawson Creek — America/Dawson_Creek" },
  { value: "America/Denver", label: "(UTC−07:00) Denver — America/Denver" },
  { value: "America/Edmonton", label: "(UTC−07:00) Edmonton — America/Edmonton" },
  { value: "America/Fort_Nelson", label: "(UTC−07:00) Fort Nelson — America/Fort_Nelson" },
  { value: "America/Hermosillo", label: "(UTC−07:00) Hermosillo — America/Hermosillo" },
  { value: "America/Inuvik", label: "(UTC−07:00) Inuvik — America/Inuvik" },
  { value: "America/Mazatlan", label: "(UTC−07:00) Mazatlan — America/Mazatlan" },
  { value: "America/Phoenix", label: "(UTC−07:00) Phoenix — America/Phoenix" },
  { value: "America/Whitehorse", label: "(UTC−07:00) Whitehorse — America/Whitehorse" },
  { value: "America/Bahia_Banderas", label: "(UTC−06:00) Bahia Banderas — America/Bahia_Banderas" },
  { value: "America/Belize", label: "(UTC−06:00) Belize — America/Belize" },
  { value: "America/Chicago", label: "(UTC−06:00) Chicago — America/Chicago" },
  { value: "America/Chihuahua", label: "(UTC−06:00) Chihuahua — America/Chihuahua" },
  { value: "America/Costa_Rica", label: "(UTC−06:00) Costa Rica — America/Costa_Rica" },
  { value: "America/El_Salvador", label: "(UTC−06:00) El Salvador — America/El_Salvador" },
  { value: "America/Guatemala", label: "(UTC−06:00) Guatemala — America/Guatemala" },
  { value: "America/Indiana/Knox", label: "(UTC−06:00) Knox — America/Indiana/Knox" },
  { value: "America/Indiana/Tell_City", label: "(UTC−06:00) Tell City — America/Indiana/Tell_City" },
  { value: "America/Managua", label: "(UTC−06:00) Managua — America/Managua" },
  { value: "America/Matamoros", label: "(UTC−06:00) Matamoros — America/Matamoros" },
  { value: "America/Menominee", label: "(UTC−06:00) Menominee — America/Menominee" },
  { value: "America/Merida", label: "(UTC−06:00) Merida — America/Merida" },
  { value: "America/Mexico_City", label: "(UTC−06:00) Mexico City — America/Mexico_City" },
  { value: "America/Monterrey", label: "(UTC−06:00) Monterrey — America/Monterrey" },
  { value: "America/North_Dakota/Beulah", label: "(UTC−06:00) Beulah — America/North_Dakota/Beulah" },
  { value: "America/North_Dakota/Center", label: "(UTC−06:00) Center — America/North_Dakota/Center" },
  { value: "America/North_Dakota/New_Salem", label: "(UTC−06:00) New Salem — America/North_Dakota/New_Salem" },
  { value: "America/Ojinaga", label: "(UTC−06:00) Ojinaga — America/Ojinaga" },
  { value: "America/Rankin_Inlet", label: "(UTC−06:00) Rankin Inlet — America/Rankin_Inlet" },
  { value: "America/Regina", label: "(UTC−06:00) Regina — America/Regina" },
  { value: "America/Resolute", label: "(UTC−06:00) Resolute — America/Resolute" },
  { value: "America/Swift_Current", label: "(UTC−06:00) Swift Current — America/Swift_Current" },
  { value: "America/Tegucigalpa", label: "(UTC−06:00) Tegucigalpa — America/Tegucigalpa" },
  { value: "America/Winnipeg", label: "(UTC−06:00) Winnipeg — America/Winnipeg" },
  { value: "Pacific/Galapagos", label: "(UTC−06:00) Galapagos — Pacific/Galapagos" },
  { value: "America/Bogota", label: "(UTC−05:00) Bogota — America/Bogota" },
  { value: "America/Cancun", label: "(UTC−05:00) Cancun — America/Cancun" },
  { value: "America/Cayman", label: "(UTC−05:00) Cayman — America/Cayman" },
  { value: "America/Coral_Harbour", label: "(UTC−05:00) Coral Harbour — America/Coral_Harbour" },
  { value: "America/Detroit", label: "(UTC−05:00) Detroit — America/Detroit" },
  { value: "America/Eirunepe", label: "(UTC−05:00) Eirunepe — America/Eirunepe" },
  { value: "America/Grand_Turk", label: "(UTC−05:00) Grand Turk — America/Grand_Turk" },
  { value: "America/Guayaquil", label: "(UTC−05:00) Guayaquil — America/Guayaquil" },
  { value: "America/Havana", label: "(UTC−05:00) Havana — America/Havana" },
  { value: "America/Indiana/Marengo", label: "(UTC−05:00) Marengo — America/Indiana/Marengo" },
  { value: "America/Indiana/Petersburg", label: "(UTC−05:00) Petersburg — America/Indiana/Petersburg" },
  { value: "America/Indiana/Vevay", label: "(UTC−05:00) Vevay — America/Indiana/Vevay" },
  { value: "America/Indiana/Vincennes", label: "(UTC−05:00) Vincennes — America/Indiana/Vincennes" },
  { value: "America/Indiana/Winamac", label: "(UTC−05:00) Winamac — America/Indiana/Winamac" },
  { value: "America/Indianapolis", label: "(UTC−05:00) Indianapolis — America/Indianapolis" },
  { value: "America/Iqaluit", label: "(UTC−05:00) Iqaluit — America/Iqaluit" },
  { value: "America/Jamaica", label: "(UTC−05:00) Jamaica — America/Jamaica" },
  { value: "America/Kentucky/Monticello", label: "(UTC−05:00) Monticello — America/Kentucky/Monticello" },
  { value: "America/Lima", label: "(UTC−05:00) Lima — America/Lima" },
  { value: "America/Louisville", label: "(UTC−05:00) Louisville — America/Louisville" },
  { value: "America/Nassau", label: "(UTC−05:00) Nassau — America/Nassau" },
  { value: "America/New_York", label: "(UTC−05:00) New York — America/New_York" },
  { value: "America/Panama", label: "(UTC−05:00) Panama — America/Panama" },
  { value: "America/Port-au-Prince", label: "(UTC−05:00) Port-au-Prince — America/Port-au-Prince" },
  { value: "America/Rio_Branco", label: "(UTC−05:00) Rio Branco — America/Rio_Branco" },
  { value: "America/Toronto", label: "(UTC−05:00) Toronto — America/Toronto" },
  { value: "Pacific/Easter", label: "(UTC−05:00) Easter — Pacific/Easter" },
  { value: "America/Anguilla", label: "(UTC−04:00) Anguilla — America/Anguilla" },
  { value: "America/Antigua", label: "(UTC−04:00) Antigua — America/Antigua" },
  { value: "America/Aruba", label: "(UTC−04:00) Aruba — America/Aruba" },
  { value: "America/Barbados", label: "(UTC−04:00) Barbados — America/Barbados" },
  { value: "America/Blanc-Sablon", label: "(UTC−04:00) Blanc-Sablon — America/Blanc-Sablon" },
  { value: "America/Boa_Vista", label: "(UTC−04:00) Boa Vista — America/Boa_Vista" },
  { value: "America/Campo_Grande", label: "(UTC−04:00) Campo Grande — America/Campo_Grande" },
  { value: "America/Caracas", label: "(UTC−04:00) Caracas — America/Caracas" },
  { value: "America/Cuiaba", label: "(UTC−04:00) Cuiaba — America/Cuiaba" },
  { value: "America/Curacao", label: "(UTC−04:00) Curacao — America/Curacao" },
  { value: "America/Dominica", label: "(UTC−04:00) Dominica — America/Dominica" },
  { value: "America/Glace_Bay", label: "(UTC−04:00) Glace Bay — America/Glace_Bay" },
  { value: "America/Goose_Bay", label: "(UTC−04:00) Goose Bay — America/Goose_Bay" },
  { value: "America/Grenada", label: "(UTC−04:00) Grenada — America/Grenada" },
  { value: "America/Guadeloupe", label: "(UTC−04:00) Guadeloupe — America/Guadeloupe" },
  { value: "America/Guyana", label: "(UTC−04:00) Guyana — America/Guyana" },
  { value: "America/Halifax", label: "(UTC−04:00) Halifax — America/Halifax" },
  { value: "America/Kralendijk", label: "(UTC−04:00) Kralendijk — America/Kralendijk" },
  { value: "America/La_Paz", label: "(UTC−04:00) La Paz — America/La_Paz" },
  { value: "America/Lower_Princes", label: "(UTC−04:00) Lower Princes — America/Lower_Princes" },
  { value: "America/Manaus", label: "(UTC−04:00) Manaus — America/Manaus" },
  { value: "America/Marigot", label: "(UTC−04:00) Marigot — America/Marigot" },
  { value: "America/Martinique", label: "(UTC−04:00) Martinique — America/Martinique" },
  { value: "America/Moncton", label: "(UTC−04:00) Moncton — America/Moncton" },
  { value: "America/Montserrat", label: "(UTC−04:00) Montserrat — America/Montserrat" },
  { value: "America/Port_of_Spain", label: "(UTC−04:00) Port of Spain — America/Port_of_Spain" },
  { value: "America/Porto_Velho", label: "(UTC−04:00) Porto Velho — America/Porto_Velho" },
  { value: "America/Puerto_Rico", label: "(UTC−04:00) Puerto Rico — America/Puerto_Rico" },
  { value: "America/Santo_Domingo", label: "(UTC−04:00) Santo Domingo — America/Santo_Domingo" },
  { value: "America/St_Barthelemy", label: "(UTC−04:00) St Barthelemy — America/St_Barthelemy" },
  { value: "America/St_Kitts", label: "(UTC−04:00) St Kitts — America/St_Kitts" },
  { value: "America/St_Lucia", label: "(UTC−04:00) St Lucia — America/St_Lucia" },
  { value: "America/St_Thomas", label: "(UTC−04:00) St Thomas — America/St_Thomas" },
  { value: "America/St_Vincent", label: "(UTC−04:00) St Vincent — America/St_Vincent" },
  { value: "America/Thule", label: "(UTC−04:00) Thule — America/Thule" },
  { value: "America/Tortola", label: "(UTC−04:00) Tortola — America/Tortola" },
  { value: "Atlantic/Bermuda", label: "(UTC−04:00) Bermuda — Atlantic/Bermuda" },
  { value: "America/St_Johns", label: "(UTC−03:30) St Johns — America/St_Johns" },
  { value: "America/Araguaina", label: "(UTC−03:00) Araguaina — America/Araguaina" },
  { value: "America/Argentina/La_Rioja", label: "(UTC−03:00) La Rioja — America/Argentina/La_Rioja" },
  { value: "America/Argentina/Rio_Gallegos", label: "(UTC−03:00) Rio Gallegos — America/Argentina/Rio_Gallegos" },
  { value: "America/Argentina/Salta", label: "(UTC−03:00) Salta — America/Argentina/Salta" },
  { value: "America/Argentina/San_Juan", label: "(UTC−03:00) San Juan — America/Argentina/San_Juan" },
  { value: "America/Argentina/San_Luis", label: "(UTC−03:00) San Luis — America/Argentina/San_Luis" },
  { value: "America/Argentina/Tucuman", label: "(UTC−03:00) Tucuman — America/Argentina/Tucuman" },
  { value: "America/Argentina/Ushuaia", label: "(UTC−03:00) Ushuaia — America/Argentina/Ushuaia" },
  { value: "America/Asuncion", label: "(UTC−03:00) Asuncion — America/Asuncion" },
  { value: "America/Bahia", label: "(UTC−03:00) Bahia — America/Bahia" },
  { value: "America/Belem", label: "(UTC−03:00) Belem — America/Belem" },
  { value: "America/Buenos_Aires", label: "(UTC−03:00) Buenos Aires — America/Buenos_Aires" },
  { value: "America/Catamarca", label: "(UTC−03:00) Catamarca — America/Catamarca" },
  { value: "America/Cayenne", label: "(UTC−03:00) Cayenne — America/Cayenne" },
  { value: "America/Cordoba", label: "(UTC−03:00) Cordoba — America/Cordoba" },
  { value: "America/Coyhaique", label: "(UTC−03:00) Coyhaique — America/Coyhaique" },
  { value: "America/Fortaleza", label: "(UTC−03:00) Fortaleza — America/Fortaleza" },
  { value: "America/Jujuy", label: "(UTC−03:00) Jujuy — America/Jujuy" },
  { value: "America/Maceio", label: "(UTC−03:00) Maceio — America/Maceio" },
  { value: "America/Mendoza", label: "(UTC−03:00) Mendoza — America/Mendoza" },
  { value: "America/Miquelon", label: "(UTC−03:00) Miquelon — America/Miquelon" },
  { value: "America/Montevideo", label: "(UTC−03:00) Montevideo — America/Montevideo" },
  { value: "America/Paramaribo", label: "(UTC−03:00) Paramaribo — America/Paramaribo" },
  { value: "America/Punta_Arenas", label: "(UTC−03:00) Punta Arenas — America/Punta_Arenas" },
  { value: "America/Recife", label: "(UTC−03:00) Recife — America/Recife" },
  { value: "America/Santarem", label: "(UTC−03:00) Santarem — America/Santarem" },
  { value: "America/Santiago", label: "(UTC−03:00) Santiago — America/Santiago" },
  { value: "America/Sao_Paulo", label: "(UTC−03:00) Sao Paulo — America/Sao_Paulo" },
  { value: "Antarctica/Palmer", label: "(UTC−03:00) Palmer — Antarctica/Palmer" },
  { value: "Antarctica/Rothera", label: "(UTC−03:00) Rothera — Antarctica/Rothera" },
  { value: "Atlantic/Stanley", label: "(UTC−03:00) Stanley — Atlantic/Stanley" },
  { value: "America/Godthab", label: "(UTC−02:00) Godthab — America/Godthab" },
  { value: "America/Noronha", label: "(UTC−02:00) Noronha — America/Noronha" },
  { value: "America/Scoresbysund", label: "(UTC−02:00) Scoresbysund — America/Scoresbysund" },
  { value: "Atlantic/South_Georgia", label: "(UTC−02:00) South Georgia — Atlantic/South_Georgia" },
  { value: "Atlantic/Azores", label: "(UTC−01:00) Azores — Atlantic/Azores" },
  { value: "Atlantic/Cape_Verde", label: "(UTC−01:00) Cape Verde — Atlantic/Cape_Verde" },
  { value: "Africa/Abidjan", label: "(UTC+00:00) Abidjan — Africa/Abidjan" },
  { value: "Africa/Accra", label: "(UTC+00:00) Accra — Africa/Accra" },
  { value: "Africa/Bamako", label: "(UTC+00:00) Bamako — Africa/Bamako" },
  { value: "Africa/Banjul", label: "(UTC+00:00) Banjul — Africa/Banjul" },
  { value: "Africa/Bissau", label: "(UTC+00:00) Bissau — Africa/Bissau" },
  { value: "Africa/Conakry", label: "(UTC+00:00) Conakry — Africa/Conakry" },
  { value: "Africa/Dakar", label: "(UTC+00:00) Dakar — Africa/Dakar" },
  { value: "Africa/Freetown", label: "(UTC+00:00) Freetown — Africa/Freetown" },
  { value: "Africa/Lome", label: "(UTC+00:00) Lome — Africa/Lome" },
  { value: "Africa/Monrovia", label: "(UTC+00:00) Monrovia — Africa/Monrovia" },
  { value: "Africa/Nouakchott", label: "(UTC+00:00) Nouakchott — Africa/Nouakchott" },
  { value: "Africa/Ouagadougou", label: "(UTC+00:00) Ouagadougou — Africa/Ouagadougou" },
  { value: "Africa/Sao_Tome", label: "(UTC+00:00) Sao Tome — Africa/Sao_Tome" },
  { value: "America/Danmarkshavn", label: "(UTC+00:00) Danmarkshavn — America/Danmarkshavn" },
  { value: "Antarctica/Troll", label: "(UTC+00:00) Troll — Antarctica/Troll" },
  { value: "Atlantic/Canary", label: "(UTC+00:00) Canary — Atlantic/Canary" },
  { value: "Atlantic/Faeroe", label: "(UTC+00:00) Faeroe — Atlantic/Faeroe" },
  { value: "Atlantic/Madeira", label: "(UTC+00:00) Madeira — Atlantic/Madeira" },
  { value: "Atlantic/Reykjavik", label: "(UTC+00:00) Reykjavik — Atlantic/Reykjavik" },
  { value: "Atlantic/St_Helena", label: "(UTC+00:00) St Helena — Atlantic/St_Helena" },
  { value: "Europe/Dublin", label: "(UTC+00:00) Dublin — Europe/Dublin" },
  { value: "Europe/Guernsey", label: "(UTC+00:00) Guernsey — Europe/Guernsey" },
  { value: "Europe/Isle_of_Man", label: "(UTC+00:00) Isle of Man — Europe/Isle_of_Man" },
  { value: "Europe/Jersey", label: "(UTC+00:00) Jersey — Europe/Jersey" },
  { value: "Europe/Lisbon", label: "(UTC+00:00) Lisbon — Europe/Lisbon" },
  { value: "Europe/London", label: "(UTC+00:00) London — Europe/London" },
  { value: "Africa/Algiers", label: "(UTC+01:00) Algiers — Africa/Algiers" },
  { value: "Africa/Bangui", label: "(UTC+01:00) Bangui — Africa/Bangui" },
  { value: "Africa/Brazzaville", label: "(UTC+01:00) Brazzaville — Africa/Brazzaville" },
  { value: "Africa/Casablanca", label: "(UTC+01:00) Casablanca — Africa/Casablanca" },
  { value: "Africa/Ceuta", label: "(UTC+01:00) Ceuta — Africa/Ceuta" },
  { value: "Africa/Douala", label: "(UTC+01:00) Douala — Africa/Douala" },
  { value: "Africa/El_Aaiun", label: "(UTC+01:00) El Aaiun — Africa/El_Aaiun" },
  { value: "Africa/Kinshasa", label: "(UTC+01:00) Kinshasa — Africa/Kinshasa" },
  { value: "Africa/Lagos", label: "(UTC+01:00) Lagos — Africa/Lagos" },
  { value: "Africa/Libreville", label: "(UTC+01:00) Libreville — Africa/Libreville" },
  { value: "Africa/Luanda", label: "(UTC+01:00) Luanda — Africa/Luanda" },
  { value: "Africa/Malabo", label: "(UTC+01:00) Malabo — Africa/Malabo" },
  { value: "Africa/Ndjamena", label: "(UTC+01:00) Ndjamena — Africa/Ndjamena" },
  { value: "Africa/Niamey", label: "(UTC+01:00) Niamey — Africa/Niamey" },
  { value: "Africa/Porto-Novo", label: "(UTC+01:00) Porto-Novo — Africa/Porto-Novo" },
  { value: "Africa/Tunis", label: "(UTC+01:00) Tunis — Africa/Tunis" },
  { value: "Arctic/Longyearbyen", label: "(UTC+01:00) Longyearbyen — Arctic/Longyearbyen" },
  { value: "Europe/Amsterdam", label: "(UTC+01:00) Amsterdam — Europe/Amsterdam" },
  { value: "Europe/Andorra", label: "(UTC+01:00) Andorra — Europe/Andorra" },
  { value: "Europe/Belgrade", label: "(UTC+01:00) Belgrade — Europe/Belgrade" },
  { value: "Europe/Berlin", label: "(UTC+01:00) Berlin — Europe/Berlin" },
  { value: "Europe/Bratislava", label: "(UTC+01:00) Bratislava — Europe/Bratislava" },
  { value: "Europe/Brussels", label: "(UTC+01:00) Brussels — Europe/Brussels" },
  { value: "Europe/Budapest", label: "(UTC+01:00) Budapest — Europe/Budapest" },
  { value: "Europe/Busingen", label: "(UTC+01:00) Busingen — Europe/Busingen" },
  { value: "Europe/Copenhagen", label: "(UTC+01:00) Copenhagen — Europe/Copenhagen" },
  { value: "Europe/Gibraltar", label: "(UTC+01:00) Gibraltar — Europe/Gibraltar" },
  { value: "Europe/Ljubljana", label: "(UTC+01:00) Ljubljana — Europe/Ljubljana" },
  { value: "Europe/Luxembourg", label: "(UTC+01:00) Luxembourg — Europe/Luxembourg" },
  { value: "Europe/Madrid", label: "(UTC+01:00) Madrid — Europe/Madrid" },
  { value: "Europe/Malta", label: "(UTC+01:00) Malta — Europe/Malta" },
  { value: "Europe/Monaco", label: "(UTC+01:00) Monaco — Europe/Monaco" },
  { value: "Europe/Oslo", label: "(UTC+01:00) Oslo — Europe/Oslo" },
  { value: "Europe/Paris", label: "(UTC+01:00) Paris — Europe/Paris" },
  { value: "Europe/Podgorica", label: "(UTC+01:00) Podgorica — Europe/Podgorica" },
  { value: "Europe/Prague", label: "(UTC+01:00) Prague — Europe/Prague" },
  { value: "Europe/Rome", label: "(UTC+01:00) Rome — Europe/Rome" },
  { value: "Europe/San_Marino", label: "(UTC+01:00) San Marino — Europe/San_Marino" },
  { value: "Europe/Sarajevo", label: "(UTC+01:00) Sarajevo — Europe/Sarajevo" },
  { value: "Europe/Skopje", label: "(UTC+01:00) Skopje — Europe/Skopje" },
  { value: "Europe/Stockholm", label: "(UTC+01:00) Stockholm — Europe/Stockholm" },
  { value: "Europe/Tirane", label: "(UTC+01:00) Tirane — Europe/Tirane" },
  { value: "Europe/Vaduz", label: "(UTC+01:00) Vaduz — Europe/Vaduz" },
  { value: "Europe/Vatican", label: "(UTC+01:00) Vatican — Europe/Vatican" },
  { value: "Europe/Vienna", label: "(UTC+01:00) Vienna — Europe/Vienna" },
  { value: "Europe/Warsaw", label: "(UTC+01:00) Warsaw — Europe/Warsaw" },
  { value: "Europe/Zagreb", label: "(UTC+01:00) Zagreb — Europe/Zagreb" },
  { value: "Europe/Zurich", label: "(UTC+01:00) Zurich — Europe/Zurich" },
  { value: "Africa/Blantyre", label: "(UTC+02:00) Blantyre — Africa/Blantyre" },
  { value: "Africa/Bujumbura", label: "(UTC+02:00) Bujumbura — Africa/Bujumbura" },
  { value: "Africa/Cairo", label: "(UTC+02:00) Cairo — Africa/Cairo" },
  { value: "Africa/Gaborone", label: "(UTC+02:00) Gaborone — Africa/Gaborone" },
  { value: "Africa/Harare", label: "(UTC+02:00) Harare — Africa/Harare" },
  { value: "Africa/Johannesburg", label: "(UTC+02:00) Johannesburg — Africa/Johannesburg" },
  { value: "Africa/Juba", label: "(UTC+02:00) Juba — Africa/Juba" },
  { value: "Africa/Khartoum", label: "(UTC+02:00) Khartoum — Africa/Khartoum" },
  { value: "Africa/Kigali", label: "(UTC+02:00) Kigali — Africa/Kigali" },
  { value: "Africa/Lubumbashi", label: "(UTC+02:00) Lubumbashi — Africa/Lubumbashi" },
  { value: "Africa/Lusaka", label: "(UTC+02:00) Lusaka — Africa/Lusaka" },
  { value: "Africa/Maputo", label: "(UTC+02:00) Maputo — Africa/Maputo" },
  { value: "Africa/Maseru", label: "(UTC+02:00) Maseru — Africa/Maseru" },
  { value: "Africa/Mbabane", label: "(UTC+02:00) Mbabane — Africa/Mbabane" },
  { value: "Africa/Tripoli", label: "(UTC+02:00) Tripoli — Africa/Tripoli" },
  { value: "Africa/Windhoek", label: "(UTC+02:00) Windhoek — Africa/Windhoek" },
  { value: "Asia/Beirut", label: "(UTC+02:00) Beirut — Asia/Beirut" },
  { value: "Asia/Famagusta", label: "(UTC+02:00) Famagusta — Asia/Famagusta" },
  { value: "Asia/Gaza", label: "(UTC+02:00) Gaza — Asia/Gaza" },
  { value: "Asia/Hebron", label: "(UTC+02:00) Hebron — Asia/Hebron" },
  { value: "Asia/Jerusalem", label: "(UTC+02:00) Jerusalem — Asia/Jerusalem" },
  { value: "Asia/Nicosia", label: "(UTC+02:00) Nicosia — Asia/Nicosia" },
  { value: "Europe/Athens", label: "(UTC+02:00) Athens — Europe/Athens" },
  { value: "Europe/Bucharest", label: "(UTC+02:00) Bucharest — Europe/Bucharest" },
  { value: "Europe/Chisinau", label: "(UTC+02:00) Chisinau — Europe/Chisinau" },
  { value: "Europe/Helsinki", label: "(UTC+02:00) Helsinki — Europe/Helsinki" },
  { value: "Europe/Kaliningrad", label: "(UTC+02:00) Kaliningrad — Europe/Kaliningrad" },
  { value: "Europe/Kiev", label: "(UTC+02:00) Kiev — Europe/Kiev" },
  { value: "Europe/Mariehamn", label: "(UTC+02:00) Mariehamn — Europe/Mariehamn" },
  { value: "Europe/Riga", label: "(UTC+02:00) Riga — Europe/Riga" },
  { value: "Europe/Sofia", label: "(UTC+02:00) Sofia — Europe/Sofia" },
  { value: "Europe/Tallinn", label: "(UTC+02:00) Tallinn — Europe/Tallinn" },
  { value: "Europe/Vilnius", label: "(UTC+02:00) Vilnius — Europe/Vilnius" },
  { value: "Africa/Addis_Ababa", label: "(UTC+03:00) Addis Ababa — Africa/Addis_Ababa" },
  { value: "Africa/Asmera", label: "(UTC+03:00) Asmera — Africa/Asmera" },
  { value: "Africa/Dar_es_Salaam", label: "(UTC+03:00) Dar es Salaam — Africa/Dar_es_Salaam" },
  { value: "Africa/Djibouti", label: "(UTC+03:00) Djibouti — Africa/Djibouti" },
  { value: "Africa/Kampala", label: "(UTC+03:00) Kampala — Africa/Kampala" },
  { value: "Africa/Mogadishu", label: "(UTC+03:00) Mogadishu — Africa/Mogadishu" },
  { value: "Africa/Nairobi", label: "(UTC+03:00) Nairobi — Africa/Nairobi" },
  { value: "Antarctica/Syowa", label: "(UTC+03:00) Syowa — Antarctica/Syowa" },
  { value: "Asia/Aden", label: "(UTC+03:00) Aden — Asia/Aden" },
  { value: "Asia/Amman", label: "(UTC+03:00) Amman — Asia/Amman" },
  { value: "Asia/Baghdad", label: "(UTC+03:00) Baghdad — Asia/Baghdad" },
  { value: "Asia/Bahrain", label: "(UTC+03:00) Bahrain — Asia/Bahrain" },
  { value: "Asia/Damascus", label: "(UTC+03:00) Damascus — Asia/Damascus" },
  { value: "Asia/Kuwait", label: "(UTC+03:00) Kuwait — Asia/Kuwait" },
  { value: "Asia/Qatar", label: "(UTC+03:00) Qatar — Asia/Qatar" },
  { value: "Asia/Riyadh", label: "(UTC+03:00) Riyadh — Asia/Riyadh" },
  { value: "Europe/Istanbul", label: "(UTC+03:00) Istanbul — Europe/Istanbul" },
  { value: "Europe/Kirov", label: "(UTC+03:00) Kirov — Europe/Kirov" },
  { value: "Europe/Minsk", label: "(UTC+03:00) Minsk — Europe/Minsk" },
  { value: "Europe/Moscow", label: "(UTC+03:00) Moscow — Europe/Moscow" },
  { value: "Europe/Simferopol", label: "(UTC+03:00) Simferopol — Europe/Simferopol" },
  { value: "Europe/Volgograd", label: "(UTC+03:00) Volgograd — Europe/Volgograd" },
  { value: "Indian/Antananarivo", label: "(UTC+03:00) Antananarivo — Indian/Antananarivo" },
  { value: "Indian/Comoro", label: "(UTC+03:00) Comoro — Indian/Comoro" },
  { value: "Indian/Mayotte", label: "(UTC+03:00) Mayotte — Indian/Mayotte" },
  { value: "Asia/Tehran", label: "(UTC+03:30) Tehran — Asia/Tehran" },
  { value: "Asia/Baku", label: "(UTC+04:00) Baku — Asia/Baku" },
  { value: "Asia/Dubai", label: "(UTC+04:00) Dubai — Asia/Dubai" },
  { value: "Asia/Muscat", label: "(UTC+04:00) Muscat — Asia/Muscat" },
  { value: "Asia/Tbilisi", label: "(UTC+04:00) Tbilisi — Asia/Tbilisi" },
  { value: "Asia/Yerevan", label: "(UTC+04:00) Yerevan — Asia/Yerevan" },
  { value: "Europe/Astrakhan", label: "(UTC+04:00) Astrakhan — Europe/Astrakhan" },
  { value: "Europe/Samara", label: "(UTC+04:00) Samara — Europe/Samara" },
  { value: "Europe/Saratov", label: "(UTC+04:00) Saratov — Europe/Saratov" },
  { value: "Europe/Ulyanovsk", label: "(UTC+04:00) Ulyanovsk — Europe/Ulyanovsk" },
  { value: "Indian/Mahe", label: "(UTC+04:00) Mahe — Indian/Mahe" },
  { value: "Indian/Mauritius", label: "(UTC+04:00) Mauritius — Indian/Mauritius" },
  { value: "Indian/Reunion", label: "(UTC+04:00) Reunion — Indian/Reunion" },
  { value: "Asia/Kabul", label: "(UTC+04:30) Kabul — Asia/Kabul" },
  { value: "Antarctica/Mawson", label: "(UTC+05:00) Mawson — Antarctica/Mawson" },
  { value: "Antarctica/Vostok", label: "(UTC+05:00) Vostok — Antarctica/Vostok" },
  { value: "Asia/Almaty", label: "(UTC+05:00) Almaty — Asia/Almaty" },
  { value: "Asia/Aqtau", label: "(UTC+05:00) Aqtau — Asia/Aqtau" },
  { value: "Asia/Aqtobe", label: "(UTC+05:00) Aqtobe — Asia/Aqtobe" },
  { value: "Asia/Ashgabat", label: "(UTC+05:00) Ashgabat — Asia/Ashgabat" },
  { value: "Asia/Atyrau", label: "(UTC+05:00) Atyrau — Asia/Atyrau" },
  { value: "Asia/Dushanbe", label: "(UTC+05:00) Dushanbe — Asia/Dushanbe" },
  { value: "Asia/Karachi", label: "(UTC+05:00) Karachi — Asia/Karachi" },
  { value: "Asia/Oral", label: "(UTC+05:00) Oral — Asia/Oral" },
  { value: "Asia/Qostanay", label: "(UTC+05:00) Qostanay — Asia/Qostanay" },
  { value: "Asia/Qyzylorda", label: "(UTC+05:00) Qyzylorda — Asia/Qyzylorda" },
  { value: "Asia/Samarkand", label: "(UTC+05:00) Samarkand — Asia/Samarkand" },
  { value: "Asia/Tashkent", label: "(UTC+05:00) Tashkent — Asia/Tashkent" },
  { value: "Asia/Yekaterinburg", label: "(UTC+05:00) Yekaterinburg — Asia/Yekaterinburg" },
  { value: "Indian/Kerguelen", label: "(UTC+05:00) Kerguelen — Indian/Kerguelen" },
  { value: "Indian/Maldives", label: "(UTC+05:00) Maldives — Indian/Maldives" },
  { value: "Asia/Calcutta", label: "(UTC+05:30) Calcutta — Asia/Calcutta" },
  { value: "Asia/Colombo", label: "(UTC+05:30) Colombo — Asia/Colombo" },
  { value: "Asia/Katmandu", label: "(UTC+05:45) Katmandu — Asia/Katmandu" },
  { value: "Asia/Bishkek", label: "(UTC+06:00) Bishkek — Asia/Bishkek" },
  { value: "Asia/Dhaka", label: "(UTC+06:00) Dhaka — Asia/Dhaka" },
  { value: "Asia/Omsk", label: "(UTC+06:00) Omsk — Asia/Omsk" },
  { value: "Asia/Thimphu", label: "(UTC+06:00) Thimphu — Asia/Thimphu" },
  { value: "Asia/Urumqi", label: "(UTC+06:00) Urumqi — Asia/Urumqi" },
  { value: "Indian/Chagos", label: "(UTC+06:00) Chagos — Indian/Chagos" },
  { value: "Asia/Rangoon", label: "(UTC+06:30) Rangoon — Asia/Rangoon" },
  { value: "Indian/Cocos", label: "(UTC+06:30) Cocos — Indian/Cocos" },
  { value: "Antarctica/Davis", label: "(UTC+07:00) Davis — Antarctica/Davis" },
  { value: "Asia/Bangkok", label: "(UTC+07:00) Bangkok — Asia/Bangkok" },
  { value: "Asia/Barnaul", label: "(UTC+07:00) Barnaul — Asia/Barnaul" },
  { value: "Asia/Hovd", label: "(UTC+07:00) Hovd — Asia/Hovd" },
  { value: "Asia/Jakarta", label: "(UTC+07:00) Jakarta — Asia/Jakarta" },
  { value: "Asia/Krasnoyarsk", label: "(UTC+07:00) Krasnoyarsk — Asia/Krasnoyarsk" },
  { value: "Asia/Novokuznetsk", label: "(UTC+07:00) Novokuznetsk — Asia/Novokuznetsk" },
  { value: "Asia/Novosibirsk", label: "(UTC+07:00) Novosibirsk — Asia/Novosibirsk" },
  { value: "Asia/Phnom_Penh", label: "(UTC+07:00) Phnom Penh — Asia/Phnom_Penh" },
  { value: "Asia/Pontianak", label: "(UTC+07:00) Pontianak — Asia/Pontianak" },
  { value: "Asia/Saigon", label: "(UTC+07:00) Saigon — Asia/Saigon" },
  { value: "Asia/Tomsk", label: "(UTC+07:00) Tomsk — Asia/Tomsk" },
  { value: "Asia/Vientiane", label: "(UTC+07:00) Vientiane — Asia/Vientiane" },
  { value: "Indian/Christmas", label: "(UTC+07:00) Christmas — Indian/Christmas" },
  { value: "Antarctica/Casey", label: "(UTC+08:00) Casey — Antarctica/Casey" },
  { value: "Asia/Brunei", label: "(UTC+08:00) Brunei — Asia/Brunei" },
  { value: "Asia/Hong_Kong", label: "(UTC+08:00) Hong Kong — Asia/Hong_Kong" },
  { value: "Asia/Irkutsk", label: "(UTC+08:00) Irkutsk — Asia/Irkutsk" },
  { value: "Asia/Kuala_Lumpur", label: "(UTC+08:00) Kuala Lumpur — Asia/Kuala_Lumpur" },
  { value: "Asia/Kuching", label: "(UTC+08:00) Kuching — Asia/Kuching" },
  { value: "Asia/Macau", label: "(UTC+08:00) Macau — Asia/Macau" },
  { value: "Asia/Makassar", label: "(UTC+08:00) Makassar — Asia/Makassar" },
  { value: "Asia/Manila", label: "(UTC+08:00) Manila — Asia/Manila" },
  { value: "Asia/Shanghai", label: "(UTC+08:00) Shanghai — Asia/Shanghai" },
  { value: "Asia/Singapore", label: "(UTC+08:00) Singapore — Asia/Singapore" },
  { value: "Asia/Taipei", label: "(UTC+08:00) Taipei — Asia/Taipei" },
  { value: "Asia/Ulaanbaatar", label: "(UTC+08:00) Ulaanbaatar — Asia/Ulaanbaatar" },
  { value: "Australia/Perth", label: "(UTC+08:00) Perth — Australia/Perth" },
  { value: "Australia/Eucla", label: "(UTC+08:45) Eucla — Australia/Eucla" },
  { value: "Asia/Chita", label: "(UTC+09:00) Chita — Asia/Chita" },
  { value: "Asia/Dili", label: "(UTC+09:00) Dili — Asia/Dili" },
  { value: "Asia/Jayapura", label: "(UTC+09:00) Jayapura — Asia/Jayapura" },
  { value: "Asia/Khandyga", label: "(UTC+09:00) Khandyga — Asia/Khandyga" },
  { value: "Asia/Pyongyang", label: "(UTC+09:00) Pyongyang — Asia/Pyongyang" },
  { value: "Asia/Seoul", label: "(UTC+09:00) Seoul — Asia/Seoul" },
  { value: "Asia/Tokyo", label: "(UTC+09:00) Tokyo — Asia/Tokyo" },
  { value: "Asia/Yakutsk", label: "(UTC+09:00) Yakutsk — Asia/Yakutsk" },
  { value: "Pacific/Palau", label: "(UTC+09:00) Palau — Pacific/Palau" },
  { value: "Australia/Darwin", label: "(UTC+09:30) Darwin — Australia/Darwin" },
  { value: "Antarctica/DumontDUrville", label: "(UTC+10:00) DumontDUrville — Antarctica/DumontDUrville" },
  { value: "Asia/Ust-Nera", label: "(UTC+10:00) Ust-Nera — Asia/Ust-Nera" },
  { value: "Asia/Vladivostok", label: "(UTC+10:00) Vladivostok — Asia/Vladivostok" },
  { value: "Australia/Brisbane", label: "(UTC+10:00) Brisbane — Australia/Brisbane" },
  { value: "Australia/Lindeman", label: "(UTC+10:00) Lindeman — Australia/Lindeman" },
  { value: "Pacific/Guam", label: "(UTC+10:00) Guam — Pacific/Guam" },
  { value: "Pacific/Port_Moresby", label: "(UTC+10:00) Port Moresby — Pacific/Port_Moresby" },
  { value: "Pacific/Saipan", label: "(UTC+10:00) Saipan — Pacific/Saipan" },
  { value: "Pacific/Truk", label: "(UTC+10:00) Truk — Pacific/Truk" },
  { value: "Australia/Adelaide", label: "(UTC+10:30) Adelaide — Australia/Adelaide" },
  { value: "Australia/Broken_Hill", label: "(UTC+10:30) Broken Hill — Australia/Broken_Hill" },
  { value: "Antarctica/Macquarie", label: "(UTC+11:00) Macquarie — Antarctica/Macquarie" },
  { value: "Asia/Magadan", label: "(UTC+11:00) Magadan — Asia/Magadan" },
  { value: "Asia/Sakhalin", label: "(UTC+11:00) Sakhalin — Asia/Sakhalin" },
  { value: "Asia/Srednekolymsk", label: "(UTC+11:00) Srednekolymsk — Asia/Srednekolymsk" },
  { value: "Australia/Hobart", label: "(UTC+11:00) Hobart — Australia/Hobart" },
  { value: "Australia/Lord_Howe", label: "(UTC+11:00) Lord Howe — Australia/Lord_Howe" },
  { value: "Australia/Melbourne", label: "(UTC+11:00) Melbourne — Australia/Melbourne" },
  { value: "Australia/Sydney", label: "(UTC+11:00) Sydney — Australia/Sydney" },
  { value: "Pacific/Bougainville", label: "(UTC+11:00) Bougainville — Pacific/Bougainville" },
  { value: "Pacific/Efate", label: "(UTC+11:00) Efate — Pacific/Efate" },
  { value: "Pacific/Guadalcanal", label: "(UTC+11:00) Guadalcanal — Pacific/Guadalcanal" },
  { value: "Pacific/Kosrae", label: "(UTC+11:00) Kosrae — Pacific/Kosrae" },
  { value: "Pacific/Noumea", label: "(UTC+11:00) Noumea — Pacific/Noumea" },
  { value: "Pacific/Ponape", label: "(UTC+11:00) Ponape — Pacific/Ponape" },
  { value: "Asia/Anadyr", label: "(UTC+12:00) Anadyr — Asia/Anadyr" },
  { value: "Asia/Kamchatka", label: "(UTC+12:00) Kamchatka — Asia/Kamchatka" },
  { value: "Pacific/Fiji", label: "(UTC+12:00) Fiji — Pacific/Fiji" },
  { value: "Pacific/Funafuti", label: "(UTC+12:00) Funafuti — Pacific/Funafuti" },
  { value: "Pacific/Kwajalein", label: "(UTC+12:00) Kwajalein — Pacific/Kwajalein" },
  { value: "Pacific/Majuro", label: "(UTC+12:00) Majuro — Pacific/Majuro" },
  { value: "Pacific/Nauru", label: "(UTC+12:00) Nauru — Pacific/Nauru" },
  { value: "Pacific/Norfolk", label: "(UTC+12:00) Norfolk — Pacific/Norfolk" },
  { value: "Pacific/Tarawa", label: "(UTC+12:00) Tarawa — Pacific/Tarawa" },
  { value: "Pacific/Wake", label: "(UTC+12:00) Wake — Pacific/Wake" },
  { value: "Pacific/Wallis", label: "(UTC+12:00) Wallis — Pacific/Wallis" },
  { value: "Antarctica/McMurdo", label: "(UTC+13:00) McMurdo — Antarctica/McMurdo" },
  { value: "Pacific/Apia", label: "(UTC+13:00) Apia — Pacific/Apia" },
  { value: "Pacific/Auckland", label: "(UTC+13:00) Auckland — Pacific/Auckland" },
  { value: "Pacific/Enderbury", label: "(UTC+13:00) Enderbury — Pacific/Enderbury" },
  { value: "Pacific/Fakaofo", label: "(UTC+13:00) Fakaofo — Pacific/Fakaofo" },
  { value: "Pacific/Tongatapu", label: "(UTC+13:00) Tongatapu — Pacific/Tongatapu" },
  { value: "Pacific/Chatham", label: "(UTC+13:45) Chatham — Pacific/Chatham" },
  { value: "Pacific/Kiritimati", label: "(UTC+14:00) Kiritimati — Pacific/Kiritimati" },
];

export const TIMEZONE_IDS = new Set(TIMEZONES.map((z) => z.value));

/**
 * Engines disagree on legacy zone names — Node's ICU reports Asia/Calcutta
 * where some browsers report Asia/Kolkata. Without this, auto-detecting a
 * visitor's zone silently fails for a chunk of the world, India included.
 */
const ALIASES = {
  "Asia/Kolkata": "Asia/Calcutta",
  "Asia/Calcutta": "Asia/Kolkata",
  "Asia/Ho_Chi_Minh": "Asia/Saigon",
  "Asia/Saigon": "Asia/Ho_Chi_Minh",
  "Asia/Yangon": "Asia/Rangoon",
  "Asia/Rangoon": "Asia/Yangon",
  "Asia/Kathmandu": "Asia/Katmandu",
  "Asia/Katmandu": "Asia/Kathmandu",
  "Europe/Kyiv": "Europe/Kiev",
  "Europe/Kiev": "Europe/Kyiv",
  "Asia/Macau": "Asia/Macao",
  "Asia/Macao": "Asia/Macau",
  "Atlantic/Faroe": "Atlantic/Faeroe",
  "Atlantic/Faeroe": "Atlantic/Faroe",
  "America/Argentina/Buenos_Aires": "America/Buenos_Aires",
  "America/Buenos_Aires": "America/Argentina/Buenos_Aires",
  "Asia/Istanbul": "Europe/Istanbul",
  "Europe/Istanbul": "Asia/Istanbul",
};

/** Returns the id actually present in TIMEZONES, or "" if we don't know it. */
export function normalizeZone(zone) {
  if (!zone) return "";
  if (TIMEZONE_IDS.has(zone)) return zone;
  const alias = ALIASES[zone];
  return alias && TIMEZONE_IDS.has(alias) ? alias : "";
}

/** Ignitho's markets, surfaced first in the picker before anyone searches. */
export const PRIORITY_ZONES = [
  "America/New_York",
  "America/Chicago",
  "America/Denver",
  "America/Los_Angeles",
  "Europe/London",
  "Europe/Stockholm",
  "Asia/Kolkata",
  "America/Costa_Rica",
]
  .map(normalizeZone)
  .filter(Boolean);
